dist: trusty
addons:
  chrome: stable
language: node_js
before_install:
- export TZ=Europe/Zurich
- export CHROME_BIN=google-chrome-stable
- gem install mdl
- npm i -g @angular/cli webpack
# greenkeeper-lockfile
cache:
  directories:
  - node_modules
before_script:
- (cd functions && npm i && webpack && cd ..)
# before_script: greenkeeper-lockfile-update
script: npm run ci
# after_script: greenkeeper-lockfile-upload
env:
  global:
    secure: "qccjXIfIhEs28sBre2YqVPFo4J2bObtT6sIvTr7XxwDMWgROP03wXp1+H2w5pz3kvbo21gNq9fURoJyAdgVKgAGVxfuDhaIy3ogLJPZWiifLo5NU/oFZzGtqA4QpobXid3bPEnmAaud5FGfBnXpNvU1/AkSpM4CLMWFOcbNbbUvZiI018Xl+AeI+UvjT+VfDubQOtXM6c0sGfmqi5//E81+i/hpdiOyDhKJL+ItuQSdi7IS9F/hTPQXZj/7znnBn6x/K11S2BhHsQggyQEtdxwUe+iohveFuxjP59ujrS7BBTuplh2SkyTallq5k/MIqmtRSrZg4aQJj74/eUh7XMUD2vJ4mNRB9g335l+VE3GzF01NfrPyVgecyAzWtrcbEDkNVYibWjKqF8KfrGvboGyNxtrF4l61O0gV74CThHDQkuY5CaYlO9E94rXxqJerAakrEXTlt4++oE11zAU77UOeUay37Npu7lcp18YIm+aaVVBGTAcHSY7cNUd54TL3idf3QwMj3Dv/n/oxxQkB28VWmAbEsjB7bLTdg66qWwmBDTj65QxxkRCNPhrrsEBu8doN8JIL0b3HC4wOoy5ru8txdUmSngXT35VkObuhM25SVMHu6Wy2ofmApoFUHSs7jnsPYxovzIY5sqhRoqd4SX12NvuTNbBzVtkZBAP0YHLM="
#   - secure: TODO
# after_success:
# - npm install -g codeclimate-test-reporter
# - CODECLIMATE_REPO_TOKEN=TODO codeclimate-test-reporter < coverage/lcov.info
# - CODECLIMATE_API_HOST=https://codebeat.co/webhooks/code_coverage CODECLIMATE_REPO_TOKEN=TODO codeclimate-test-reporter < coverage/lcov.info
# - npm install -g codacy-coverage
# - cat coverage/lcov.info | codacy-coverage
# - npm install -g codecov
# - codecov
before_deploy:
- bin/travis-before-deploy
- npm run build-prod
- (cd functions && webpack && cd ..)
deploy:
  - provider: firebase
    skip_cleanup: true
    on:
      branch: master
    token:
      secure: "JleqZMyCJzVhMXHIV2KB4VlcV57DSrXSkdP54DX1d0zbsRvvyrlnI1rMW+W1nYOQSUhWRrV9UdRSy783MXGJ/R1LUzaYRJqndKYEMqXRE4oJWGQjEWf8XC90boy4wK4Fco7SvPyqvygPhNg7PPZk95dXsdxaslCkcRcY7TMsURf7OdhT1yioavqGaa39V+/pcehsbhalnZjT6bkTQaT67BVjKATQoS7PHSsZFYnA37EnGcssDJSvEFACicPt+1LoCBV36XZkZPvUnbIDe88pfif+qtpP82nv6akWzTGZY9mdgc+aX020QAqkFXPBY8DGOddls2BehZdmV4OE1Vy4CMgrMCMAzD17KLtHP+y3dPG8Oy7NDTxniLqZLmyD8Jb8WgGe7TWCC5mxnTX1MBj9KhIQUj3dbkb3xy4LMcOTcUAvs4c1UQmnheUmmIQ9YssPZ4JFZenxzOEAO8RK+yWFwNfsfFy+ESYf9HthxXmVwxTJDQWjxSmd7vqKtdb2ZTQ+bOLNt2KrX7CHKq19VksABy3mme0uR6eXV1soJiLoebkKXQpjI4hBZyz+E4pa1SoeDZMTbKw6G509TsW7bi67+Xhtf74+Jp2WhRem5NgZJDBGn//D/4MWIP37lZVR7upX1HKbwBodidrPPlob/HVmTcOOcJekRuQt8fQbH6a2Yf0="
    project: gdg-website-master
  - provider: firebase
    skip_cleanup: true
    on:
      branch: develop
    token:
      secure: "JleqZMyCJzVhMXHIV2KB4VlcV57DSrXSkdP54DX1d0zbsRvvyrlnI1rMW+W1nYOQSUhWRrV9UdRSy783MXGJ/R1LUzaYRJqndKYEMqXRE4oJWGQjEWf8XC90boy4wK4Fco7SvPyqvygPhNg7PPZk95dXsdxaslCkcRcY7TMsURf7OdhT1yioavqGaa39V+/pcehsbhalnZjT6bkTQaT67BVjKATQoS7PHSsZFYnA37EnGcssDJSvEFACicPt+1LoCBV36XZkZPvUnbIDe88pfif+qtpP82nv6akWzTGZY9mdgc+aX020QAqkFXPBY8DGOddls2BehZdmV4OE1Vy4CMgrMCMAzD17KLtHP+y3dPG8Oy7NDTxniLqZLmyD8Jb8WgGe7TWCC5mxnTX1MBj9KhIQUj3dbkb3xy4LMcOTcUAvs4c1UQmnheUmmIQ9YssPZ4JFZenxzOEAO8RK+yWFwNfsfFy+ESYf9HthxXmVwxTJDQWjxSmd7vqKtdb2ZTQ+bOLNt2KrX7CHKq19VksABy3mme0uR6eXV1soJiLoebkKXQpjI4hBZyz+E4pa1SoeDZMTbKw6G509TsW7bi67+Xhtf74+Jp2WhRem5NgZJDBGn//D/4MWIP37lZVR7upX1HKbwBodidrPPlob/HVmTcOOcJekRuQt8fQbH6a2Yf0="
    project: gdg-website-develop
